[project]
name = "multivaciones"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "PySide6>=6.5.0",
    "pandas>=2.0.0",
    "python-dotenv>=1.1.0",
    "numpy>=1.26.4",
    "requests>=2.31.0",
    "PyYAML>=6.0.2"
]
